//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniBinderAPI.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchedPeople
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FirstPersonID { get; set; }
        public Nullable<System.Guid> SecondPersonID { get; set; }
    }
}
