//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniBinderAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Subject
    {

        
        public int Id { get; set; }
        [DataMember]
        public string SubjectName { get; set; }
        [Key]
        public int PersonID { get; set; }

        
        public virtual Person Person { get; set; }
    }
}
